url: https://heydavid-dev.github.io
baseurl: /creating-a-new-website-189

# Site settings
header_title: Welcome To Our Agency
header_subtitle: It's Nice to Have You Around

title: Awesome Website
email: your-email@domain.com
description: "This is to create a new website"


# Team names, titles and social links
people:
- name: team Kay
  pic: 1
  position: Coder
  social:
    - title: i
      url: 1
    - title: b
      url: 2
    - title: d
      url: 3

- name: team Larry
  pic: 2
  position: Manager
  social:
    - title: g
      url: 1
    - title: y
      url: 2
    - title: v
      url: 3

- name: team diana
  pic: 3
  position: Artist
  social:
    - title: p
      url: 1
    - title: w
      url: 2
    - title: s
      url: 3

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
